alter table agents add column agent_wallet_expiration_time bigint;
alter table feedbacks add column endpoint text;
alter table agents add column feedback_block_number bigint;
alter table agents add column feedback_index bigint;


CREATE or replace FUNCTION update_agent_score_and_comment_count() RETURNS TRIGGER AS $$
DECLARE
  agent_feedback_block_number bigint;
  agent_feedback_index bigint;
BEGIN
  SELECT feedback_block_number, feedback_index 
  INTO agent_feedback_block_number, agent_feedback_index
  FROM agents 
  WHERE uid = NEW.agent_uid;
  
  IF agent_feedback_block_number IS NULL THEN
    NULL;
  ELSIF NEW.block_number > agent_feedback_block_number THEN
    NULL;
  ELSIF NEW.block_number = agent_feedback_block_number AND NEW.index > agent_feedback_index THEN
    NULL;
  ELSE
    RETURN NEW;
  END IF;
  
  UPDATE agents 
  SET 
    score = score + COALESCE(NEW.score, 0),
    comment_count = comment_count + 1,
    feedback_block_number = NEW.block_number,
    feedback_index = NEW.index
  WHERE agents.uid = NEW.agent_uid;
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

drop trigger if exists update_score_and_cnt_trigger on feedbacks;
CREATE TRIGGER update_score_and_cnt_trigger
AFTER INSERT ON feedbacks
FOR EACH ROW
EXECUTE FUNCTION update_agent_score_and_comment_count();


CREATE or replace FUNCTION update_agent_score_and_comment_count_on_feedback_revoked() RETURNS TRIGGER AS $$
DECLARE
  agent_feedback_block_number bigint;
  agent_feedback_index bigint;
BEGIN
  SELECT feedback_block_number , feedback_index 
  INTO agent_feedback_block_number, agent_feedback_index
  FROM agents 
  WHERE uid = NEW.agent_uid;
  
  IF agent_feedback_block_number IS NULL THEN
    NULL;
  ELSIF NEW.block_number > agent_feedback_block_number THEN
    NULL;
  ELSIF NEW.block_number = agent_feedback_block_number AND NEW.index > agent_feedback_index THEN
    NULL;
  ELSE
    RETURN NEW;
  END IF;
  
  UPDATE agents 
  SET 
    score = score - COALESCE(OLD.score, 0),
    comment_count = GREATEST(comment_count - 1, 0),
    feedback_block_number = NEW.block_number,
    feedback_index = NEW.index
  WHERE agents.uid = NEW.agent_uid;
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;


drop trigger if exists update_agent_score_and_cnt_on_revoked_trigger on feedbacks;

CREATE TRIGGER update_agent_score_and_cnt_on_revoked_trigger
AFTER UPDATE ON feedbacks
FOR EACH ROW
WHEN (OLD.revoked = false AND NEW.revoked = true)
EXECUTE FUNCTION update_agent_score_and_comment_count_on_feedback_revoked();


