chain_list:
  - chain_id: "1"
    chain_name: "Ethereum"
    chain_logo: "https://bnbattest.s3.ap-southeast-1.amazonaws.com/agentCard/chain/eth.png"
    scan_prefix: "https://etherscan.io/"
  - chain_id: "56"
    chain_name: "BSC"
    chain_logo: "https://bnbattest.s3.ap-southeast-1.amazonaws.com/agentCard/chain/bsc.png"
    scan_prefix: "https://bscscan.com/"
  - chain_id: "8453"
    chain_name: "Base"
    chain_logo: "https://bnbattest.s3.ap-southeast-1.amazonaws.com/agentCard/chain/base.png"
    scan_prefix: "https://basescan.org/"

register_list:
  - chain_id: "56"
    identity_address: "0x8004A169FB4a3325136EB29fA0ceB6D2e539a432"
    reputation_address: "0x8004BAa17C55a88189AE136b182e5fdA19dE9b63"
    validation_address: ""
    name:  "ETH Foundation"
    description: "ETH Foundation Official Registry"
    logo_url: "https://bnbattest.s3.ap-southeast-1.amazonaws.com/agentCard/org/eth.png"

  - chain_id: "1"
    identity_address: "0x8004A169FB4a3325136EB29fA0ceB6D2e539a432"
    reputation_address: "0x8004BAa17C55a88189AE136b182e5fdA19dE9b63"
    validation_address: ""
    name: "ETH Foundation"
    description: "ETH Foundation Official Registry"
    logo_url: "https://bnbattest.s3.ap-southeast-1.amazonaws.com/agentCard/org/eth.png"

  - chain_id: "8453"
    identity_address: "0x8004A169FB4a3325136EB29fA0ceB6D2e539a432"
    reputation_address: "0x8004BAa17C55a88189AE136b182e5fdA19dE9b63"
    validation_address: ""
    name: "ETH Foundation"
    description: "ETH Foundation Official Registry"
    logo_url: "https://bnbattest.s3.ap-southeast-1.amazonaws.com/agentCard/org/eth.png"
