chain_list:
  - chain_id: "1"
    chain_name: "Ethereum"
    chain_logo: "https://bnbattest.s3.ap-southeast-1.amazonaws.com/agentCard/chain/eth.png"
    scan_prefix: "https://etherscan.io/"
  # - chain_id: "56"
  #   chain_name: "BSC"
  #   chain_logo: "https://bnbattest.s3.ap-southeast-1.amazonaws.com/agentCard/chain/bsc.png"
  #   scan_prefix: "https://bscscan.com/"

register_list:
  # - chain_id: "56"
  #   identity_address: "0x8004A818BFB912233c491871b3d84c89A494BD9e"
  #   reputation_address: "0x8004B663056A597Dffe9eCcC1965A193B7388713"
  #   validation_address: "0x8004CB39f29c09145F24Ad9dDe2A108C1A2cdfC5"
  #   name: "BAS"
  #   description: "BAS Official Registry"
  #   logo_url: "https://bnbattest.s3.ap-southeast-1.amazonaws.com/agentCard/org/bas.png"

  - chain_id: "1"
    identity_address: "0x8004A169FB4a3325136EB29fA0ceB6D2e539a432"
    reputation_address: "0x8004BAa17C55a88189AE136b182e5fdA19dE9b63"
    validation_address: ""
    name: "ETH Foundation"
    description: "ETH Foundation Official Registry"
    logo_url: "https://bnbattest.s3.ap-southeast-1.amazonaws.com/agentCard/org/eth.png"
